minimap
zardoy/prismarine-web-client pull request #147
Opened 2024-06-13 17:30 UTC by gguio

2024-06-15 11:34 UTC, zardoy commented
/deploy

2024-07-01 05:07 UTC, zardoy commented
/deploy

2024-07-07 10:34 UTC, zardoy commented
/deploy

2024-07-10 15:23 UTC, zardoy commented
/deploy

2024-07-17 17:06 UTC, gguio commented
/deploy

2024-07-17 21:17 UTC, zardoy commented
/deploy

2024-07-20 01:38 UTC, zardoy commented
/deploy

2024-07-22 13:18 UTC, zardoy commented
/deploy

2024-07-23 07:08 UTC, zardoy commented
/deploy

2024-07-23 14:44 UTC, gguio commented
/deploy

2024-08-02 21:13 UTC, zardoy commented
/deploy

2024-08-07 11:21 UTC, gguio commented
/deploy

2024-08-07 12:53 UTC, gguio commented
/deploy

2024-08-08 12:54 UTC, gguio commented
/deploy

2024-08-08 16:21 UTC, gguio commented
/deploy

2024-08-08 20:40 UTC, gguio commented on src/react/MinimapProvider.tsx
> +    if (localServer) {
this subscribe doesnt fire

2024-08-08 20:48 UTC, zardoy commented
/deploy

2024-08-09 07:12 UTC, gguio commented
/deploy

2024-08-09 09:43 UTC, gguio commented
/deploy

2024-08-11 15:28 UTC, zardoy commented
/deploy

2024-08-12 11:13 UTC, gguio commented
/deploy

2024-08-28 14:58 UTC, zardoy commented
/deploy

2024-08-29 15:34 UTC, zardoy commented
/deploy

2024-08-30 12:57 UTC, zardoy commented
/deploy

2024-08-30 15:38 UTC, gguio commented
/deploy

2024-09-02 10:56 UTC, gguio commented
/deploy

2024-09-03 07:46 UTC, gguio commented
/deploy

2024-09-03 14:06 UTC, zardoy requested changes

2024-09-03 14:06 UTC, zardoy commented on src/react/Input.tsx
> +  const [value, setValue] = useState(defaultValue ?? '')
```suggestion
  const [value, setValue] = useState(defaultValue ?? props.value ?? '')
```

2024-09-03 15:19 UTC, zardoy commented
/deploy

2024-09-11 19:06 UTC, zardoy commented
/update

2024-09-11 23:11 UTC, zardoy commented
/deploy

2024-09-11 23:14 UTC, zardoy requested changes

2024-09-11 23:14 UTC, zardoy commented on src/react/MinimapProvider.tsx
> +    console.log('version is old:', this.isOldVersion)
Useless Logging

2024-09-13 01:01 UTC, zardoy commented
/deploy

2024-09-16 05:45 UTC, gguio commented
/deploy

2024-09-16 06:51 UTC, gguio commented
/deploy

2024-09-16 08:15 UTC, gguio commented
/deploy

2024-09-16 08:21 UTC, gguio commented
/deploy

2024-09-16 08:39 UTC, gguio commented
/deploy

2024-09-16 08:52 UTC, gguio commented
/deploy

2024-09-16 10:31 UTC, gguio commented
/deploy

2024-09-23 09:14 UTC, gguio commented
/deploy

2024-09-23 09:29 UTC, gguio commented
/deploy

2024-09-23 11:12 UTC, gguio commented
/deploy

2024-10-10 08:59 UTC, gguio commented
/deploy

2024-10-20 17:21 UTC, zardoy commented
/deploy

2024-11-25 10:05 UTC, Phoenix616 commented
This looks pretty cool, is there a way to pre-configure whether its enabled or not? (e.g. via a get parameter in the URL) I took a look at the code and didn't find anything in that direction.

2024-11-25 13:25 UTC, zardoy commented
> This looks pretty cool, is there a way to pre-configure whether its enabled or not? (e.g. via a get parameter in the URL) I took a look at the code and didn't find anything in that direction.

@Phoenix616 Yes, its possible to configure almost **every aspect of the application** via parameters in the URL. Remember that you can change the setting of the application in that way: `?setting=<setting_name>:<setting_value>`. So there is an example link with minimap disabled: https://minimap.mcraft.fun/?mapDir=https%3A%2F%2Fbucket.mcraft.fun%2FGreenfield+v0.5.1%2Fmap-index.json&setting=showMinimap:"never"

@gguio

2024-11-26 14:46 UTC, zardoy commented
disabled minimap by default because of some issues on some platforms & singleplayer maps.

@Phoenix616 would you be interested to test it? the link is minimap.mcraft.fun (just set minimap setting to always)

2024-11-26 14:46 UTC, zardoy commented
/deploy

2024-11-27 20:07 UTC, merged