feat: item & maps in frame rendering
zardoy/prismarine-web-client pull request #243
Opened 2024-12-20 16:15 UTC by Phoenix616

This adds support for rendering item frames including the items in it.

What works:
- Item Frame model
- Item Frame textures
- Items inside frames and rendering of map items
- Proper rotations of items inside a frame and the frame itself

What doesn't work:
- Markers on maps, this does not seem to be supported by the Mineflayer MapDownloader plugin?

2024-12-21 19:14 UTC, zardoy commented
Wow, I'm kind of impressed. Very cool, seems you understand the code base very well :)

2024-12-23 16:02 UTC, zardoy requested changes

2024-12-23 16:02 UTC, zardoy commented on prismarine-viewer/viewer/lib/entities.ts
> +  loadTexture(imageData, texture => {
will texture be removed when the map entity is removed? from the current code it doesn't seem so, would be great if you could test:
- in console type: `viewer.renderer.info.memory.textures` - this number should not increase after removing / re-adding, thanks

2025-01-16 02:50 UTC, zardoy requested changes

2025-01-16 02:50 UTC, zardoy commented on prismarine-viewer/viewer/lib/entity/EntityMesh.js
> +    const textureInfo = world.blocksAtlasParser.getTextureInfo(blockName)
not clear what is world, worldRenderer might be a better name

2025-01-16 22:29 UTC, Phoenix616 commented
Item Frame rendering including maps and items should work properly now.

2025-01-22 17:57 UTC, zardoy commented
/deploy

2025-01-22 17:58 UTC, zardoy commented
/deploy

2025-01-30 11:18 UTC, Phoenix616 commented
@zardoy you mentioned [here](https://github.com/zardoy/minecraft-web-client/pull/253#issuecomment-2623310143) that this needs finishing but as far as I can tell it works? What needs finishing still?

2025-01-30 13:08 UTC, zardoy commented
> @zardoy you mentioned here that this needs finishing but as far as I can tell it works? What needs finishing still?

It doesn't work correctly on all versions (eg rotation on 1.21). Do you have a server with via backwards to test on all versions?

2025-01-31 15:42 UTC, Phoenix616 commented
> It doesn't work correctly on all versions (eg rotation on 1.21).

Works fine on 1.21:
![image](https://github.com/user-attachments/assets/45136983-6543-4e14-a5e1-d2d831903e49)


Also tried all versions between 1.20.4 and 1.21.4 and the rotation is correct.

2025-01-31 20:02 UTC, zardoy commented
/deploy

2025-02-01 02:46 UTC, merged